package cup;
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MINUS_MINUS = 65;
  public static final int BIT_XOR_ASSINGMENT = 46;
  public static final int IDENTIFIER = 75;
  public static final int DIVISION = 52;
  public static final int LESS_THAN = 39;
  public static final int TYPE = 19;
  public static final int GO = 9;
  public static final int GREATER_THAN = 48;
  public static final int CONST = 15;
  public static final int LEFT_ARROW = 47;
  public static final int BIT_AND_NOT_ASSIGNMENT = 71;
  public static final int BIN_SHIFT_RIGHT_ASSIGNMENT = 64;
  public static final int FUNC = 4;
  public static final int BIN_SHIFT_LEFT = 53;
  public static final int DEFER = 8;
  public static final int COMMA = 59;
  public static final int BIT_AND = 26;
  public static final int CLOSE_SQUARE_BRACKET = 42;
  public static final int BIT_XOR = 44;
  public static final int LOGICAL_OR = 38;
  public static final int MULTIPLICATION = 43;
  public static final int OPEN_PARENTHESES = 32;
  public static final int BIT_AND_ASSINGMENT = 28;
  public static final int VAR = 24;
  public static final int EXCLAMATION_POINT = 66;
  public static final int PLUS_PLUS = 56;
  public static final int PACKAGE = 13;
  public static final int LOGICAL_AND = 29;
  public static final int SELECT = 6;
  public static final int BIN_SHIFT_RIGHT = 62;
  public static final int FALLTHROUGH = 16;
  public static final int PLUS = 25;
  public static final int PERCENT = 61;
  public static final int NOT_EQUALS = 31;
  public static final int OCTAL_LITERAL = 78;
  public static final int PLUS_ASSINGMENT = 27;
  public static final int INTERFACE = 5;
  public static final int OPEN_CURLY_BRACKETS = 50;
  public static final int CHAN = 11;
  public static final int SWITCH = 14;
  public static final int FOR = 21;
  public static final int RETICENCE = 67;
  public static final int BIT_OR = 35;
  public static final int ASSINGMENT = 57;
  public static final int RETURN = 23;
  public static final int IMAGINARY_LITERAL = 77;
  public static final int ELSE = 12;
  public static final int BREAK = 2;
  public static final int BIN_SHIFT_LEFT_ASSINGMENT = 55;
  public static final int DOT = 68;
  public static final int PERCENT_EQUALS = 63;
  public static final int MAP = 10;
  public static final int CLOSE_PARENTHESES = 33;
  public static final int STRING_LITERAL = 76;
  public static final int EOF = 0;
  public static final int SEMICOLON = 60;
  public static final int DEFAULT = 3;
  public static final int MINUS_ASSINGMENT = 36;
  public static final int IMPORT = 22;
  public static final int MINUS = 34;
  public static final int FLOAT_LITERAL = 73;
  public static final int error = 1;
  public static final int DECIMAL_LITERAL = 72;
  public static final int CONTINUE = 20;
  public static final int IF = 17;
  public static final int CLOSE_CURLY_BRACKETS = 51;
  public static final int COLON = 69;
  public static final int HEX_LITERAL = 74;
  public static final int DIVISION_ASSINGMENT = 54;
  public static final int COLON_EQUALS = 58;
  public static final int CASE = 7;
  public static final int BIT_AND_NOT = 70;
  public static final int RANGE = 18;
  public static final int BIT_OR_ASSINGMENT = 37;
  public static final int MULTIPLICATION_ASSINGMENT = 45;
  public static final int OPEN_SQUARE_BRACKET = 41;
  public static final int GREATER_THAN_EQUALS = 49;
  public static final int EQUALS = 30;
  public static final int LESS_THAN_EQUALS = 40;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BREAK",
  "DEFAULT",
  "FUNC",
  "INTERFACE",
  "SELECT",
  "CASE",
  "DEFER",
  "GO",
  "MAP",
  "CHAN",
  "ELSE",
  "PACKAGE",
  "SWITCH",
  "CONST",
  "FALLTHROUGH",
  "IF",
  "RANGE",
  "TYPE",
  "CONTINUE",
  "FOR",
  "IMPORT",
  "RETURN",
  "VAR",
  "PLUS",
  "BIT_AND",
  "PLUS_ASSINGMENT",
  "BIT_AND_ASSINGMENT",
  "LOGICAL_AND",
  "EQUALS",
  "NOT_EQUALS",
  "OPEN_PARENTHESES",
  "CLOSE_PARENTHESES",
  "MINUS",
  "BIT_OR",
  "MINUS_ASSINGMENT",
  "BIT_OR_ASSINGMENT",
  "LOGICAL_OR",
  "LESS_THAN",
  "LESS_THAN_EQUALS",
  "OPEN_SQUARE_BRACKET",
  "CLOSE_SQUARE_BRACKET",
  "MULTIPLICATION",
  "BIT_XOR",
  "MULTIPLICATION_ASSINGMENT",
  "BIT_XOR_ASSINGMENT",
  "LEFT_ARROW",
  "GREATER_THAN",
  "GREATER_THAN_EQUALS",
  "OPEN_CURLY_BRACKETS",
  "CLOSE_CURLY_BRACKETS",
  "DIVISION",
  "BIN_SHIFT_LEFT",
  "DIVISION_ASSINGMENT",
  "BIN_SHIFT_LEFT_ASSINGMENT",
  "PLUS_PLUS",
  "ASSINGMENT",
  "COLON_EQUALS",
  "COMMA",
  "SEMICOLON",
  "PERCENT",
  "BIN_SHIFT_RIGHT",
  "PERCENT_EQUALS",
  "BIN_SHIFT_RIGHT_ASSIGNMENT",
  "MINUS_MINUS",
  "EXCLAMATION_POINT",
  "RETICENCE",
  "DOT",
  "COLON",
  "BIT_AND_NOT",
  "BIT_AND_NOT_ASSIGNMENT",
  "DECIMAL_LITERAL",
  "FLOAT_LITERAL",
  "HEX_LITERAL",
  "IDENTIFIER",
  "STRING_LITERAL",
  "IMAGINARY_LITERAL",
  "OCTAL_LITERAL"
  };
}

